package kernel

import "errors"

var (
	ErrChainParametersCreation          = errors.New("failed to create chain parameters")
	ErrContextOptionsCreation           = errors.New("failed to create context options")
	ErrContextCreation                  = errors.New("failed to create kernel context")
	ErrInvalidChainType                 = errors.New("invalid chain type")
	ErrBlockCreation                    = errors.New("failed to create block from raw data")
	ErrInvalidBlockData                 = errors.New("invalid block data")
	ErrInvalidBlock                     = errors.New("invalid block")
	ErrHashCalculation                  = errors.New("failed to calculate hash")
	ErrBlockDataCopy                    = errors.New("failed to copy block data")
	ErrChainstateManagerOptionsCreation = errors.New("failed to create chainstate manager options")
	ErrChainstateManagerCreation        = errors.New("failed to create chainstate manager")
	ErrInvalidBlockIndex                = errors.New("invalid block index")
	ErrBlockProcessing                  = errors.New("failed to process block")
	ErrBlockRead                        = errors.New("failed to read block from disk")
	ErrInvalidCallback                  = errors.New("invalid callback function")
	ErrLoggingConnectionCreation        = errors.New("failed to create logging connection")
	ErrTransactionCreation              = errors.New("failed to create transaction from raw data")
	ErrInvalidTransactionData           = errors.New("invalid transaction data")
	ErrScriptPubkeyCreation             = errors.New("failed to create script pubkey from raw data")
	ErrInvalidScriptPubkeyData          = errors.New("invalid script pubkey data")
	ErrInvalidScriptPubkey              = errors.New("invalid script pubkey")
	ErrScriptPubkeyDataCopy             = errors.New("failed to copy script pubkey data")
	ErrTransactionOutputCreation        = errors.New("failed to create transaction output")
	ErrInvalidTransactionOutput         = errors.New("invalid transaction output")
	ErrScriptPubkeyCopyFromOutput       = errors.New("failed to copy script pubkey from output")
	ErrBlockUndoRead                    = errors.New("failed to read block undo from disk")
	ErrInvalidBlockUndo                 = errors.New("invalid block undo")
	ErrUndoOutputRetrieval              = errors.New("failed to retrieve undo output")
)
